# personal aliases
alias vi="vim"
alias g++="g++ -std=c++11"
alias py="python3"
alias rdm="vi README.md"
alias sl="ls --color=auto"
alias lls="ls --color=auto"
alias lss="ls --color=auto"
alias ls="ls --color=auto"
alias cwd="pwd"
alias лс="ls"
alias цд="cd"
alias жи="vi"
alias pw="poweroff"
alias ghcc="ghc -o exe --make"
alias pmr="python manage.py runserver"
alias pms="python manage.py shell"
alias pmm="python manage.py migrate"
alias pmmm="python manage.py makemigrations"
alias pmt="python manage.py test"
alias nb="cd ~/netbeans-8.2/bin/ && ./netbeans"
alias viconf="vi ~/.vimrc"
alias zshconf="vi ~/.zshrc"
alias plovdiv="pwd"
alias c="clear"
alias locky="lock -gpf Z003-MediumItalic -- scrot -z"
alias netctl="sudo netctl"
alias pls="netctl restart $1"
alias wbuild="npm run build && python manage.py runserver"
alias ipy="ipython"
alias ivan="pytest --capture=no"
alias ghci="stack ghci"
alias b="~/dotfiles/Scripts/brightness.sh $1"
